/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package showDisplay;

import run.MainRun;
import entity.User;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtEmailRegisterForm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsernameRegiserForm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRePasswordRegisterForm = new javax.swing.JPasswordField();
        txtPasswordRegisterForm = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtPhoneRegisterForm = new javax.swing.JTextField();
        femaleCheckbox = new javax.swing.JCheckBox();
        maleCheckbox = new javax.swing.JCheckBox();
        registerBtn = new javax.swing.JButton();
        registerBtn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("REGISTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setText("Email :");

        jLabel2.setText("Username :");

        jLabel3.setText("Password :");

        jLabel4.setText("Confirm password :");

        jLabel5.setText("Phone");

        txtPhoneRegisterForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneRegisterFormActionPerformed(evt);
            }
        });

        buttonGroup1.add(femaleCheckbox);
        femaleCheckbox.setText("Female");

        buttonGroup1.add(maleCheckbox);
        maleCheckbox.setText("Male");
        maleCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleCheckboxActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        registerBtn1.setText("Return");
        registerBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtn1ActionPerformed(evt);
            }
        });

        jLabel7.setText("( 7 to 15 characters, at least 1 uppercase character, 1 special character (. , - _ ;) )");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPhoneRegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maleCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtUsernameRegiserForm, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                        .addComponent(txtPasswordRegisterForm)
                        .addComponent(txtRePasswordRegisterForm)
                        .addComponent(txtEmailRegisterForm)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernameRegiserForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordRegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRePasswordRegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailRegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneRegisterForm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleCheckbox)
                    .addComponent(maleCheckbox)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtn1ActionPerformed

        LogOrRegForm  logOrRegForm = new LogOrRegForm();
        logOrRegForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerBtn1ActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed

        User user = new User();
        StringBuilder sb = new StringBuilder();
        String username = txtUsernameRegiserForm.getText();
        String password = txtPasswordRegisterForm.getText();
        String rePassword = txtRePasswordRegisterForm.getText();
        String phone = txtPhoneRegisterForm.getText();
        String email = txtEmailRegisterForm.getText();
        while(true){
            try{
                if(username.equals("")){
            sb.append("Username is required!\n");
            txtUsernameRegiserForm.setBackground(Color.red);
        }else{
            txtUsernameRegiserForm.setBackground(Color.green);
        }
        for(int i =0;i<MainRun.users.size();i++){
            if(username.equals(MainRun.users.get(i).getUserName())){
                sb.append("This username is already exist!");
                txtUsernameRegiserForm.setBackground(Color.red);
            }else{
                txtUsernameRegiserForm.setBackground(Color.green);
            }
        }
        String regexPatternPass = "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*_-]).{7,15}$";
        if(password.equals("")){
            sb.append("Password is required!\n");
            txtPasswordRegisterForm.setBackground(Color.red);
            txtRePasswordRegisterForm.setBackground(Color.red);
        }
        else if(rePassword.equals("") && !password.equals(rePassword)){
            sb.append("ComfirmPass is not valid!\n");
            txtRePasswordRegisterForm.setBackground(Color.red);
        }else if(!rePassword.equals("") && !password.equals(rePassword)){
            sb.append("ComfirmPass is not valid!\n");
            txtRePasswordRegisterForm.setBackground(Color.red);
        }
        else if(rePassword.equals("") && password.equals(rePassword)){
            sb.append("ComfirmPass is required!\n");
            txtRePasswordRegisterForm.setBackground(Color.red);
            txtPasswordRegisterForm.setBackground(Color.red);
        }
        else if(!Pattern.compile(regexPatternPass).matcher(password).matches()){
             sb.append("Invalid password form!\n");
            txtPasswordRegisterForm.setBackground(Color.red);
        }
        else{
            txtRePasswordRegisterForm.setBackground(Color.green);
            txtPasswordRegisterForm.setBackground(Color.green);
        }
        String regexPatternEmail = "^(.+)@(\\S+)$";
        if(email.equals("")){
            sb.append("Email is required!\n");
            txtEmailRegisterForm.setBackground(Color.red);
        }else if(!Pattern.compile(regexPatternEmail).matcher(email).matches()){
            sb.append("Invalid email form!");
            txtEmailRegisterForm.setBackground(Color.red);
        }
        else{
            txtEmailRegisterForm.setBackground(Color.green);
        }
        if(phone.equals("")){
            sb.append("Phone is required!\n");
            txtPhoneRegisterForm.setBackground(Color.red);
        }else{
            txtPhoneRegisterForm.setBackground(Color.green);
            
        }
        boolean isMale = maleCheckbox.isSelected();
        boolean isFemale = femaleCheckbox.isSelected();

        if(isMale){
            user.setSex("male");
            maleCheckbox.setBackground(Color.green);
            femaleCheckbox.setBackground(Color.green);
        }else if(isFemale){
            user.setSex("female");
            maleCheckbox.setBackground(Color.green);
            femaleCheckbox.setBackground(Color.green);
        }else{
            sb.append("Sex checkbox is required!");
            maleCheckbox.setBackground(Color.red);
            femaleCheckbox.setBackground(Color.red);
        }
            
        for(int i =0;i<MainRun.users.size();i++){
            if(MainRun.users.size()>0){
                if(email.equals(MainRun.users.get(i).getEmail()) || username.equals(MainRun.users.get(i).getUserName())){
                sb.append("This acount is already exist! Enter another acount!");
                txtEmailRegisterForm.setBackground(Color.red);
                txtUsernameRegiserForm.setBackground(Color.red);
            }
            }
        }
        break;
            }catch(Exception e){
                sb.append("Invalid input type!");
            }
        }

        if(sb.length()>0){
            JOptionPane.showMessageDialog(this, sb.toString());
            return;
        }
        JOptionPane.showMessageDialog(this, "Register compelete! Please login again!");
        
        txtUsernameRegiserForm.setBackground(Color.green);
        txtPasswordRegisterForm.setBackground(Color.green);
        txtPhoneRegisterForm.setBackground(Color.green);
        txtEmailRegisterForm.setBackground(Color.green);
        
        user.setUserName(username);
        user.setPassword(password);
        user.setEmail(email);
        user.setPhone(phone);
        MainRun.users.add(user);
        LoginForm loginForm = new LoginForm();
        loginForm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_registerBtnActionPerformed

    private void maleCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleCheckboxActionPerformed

    private void txtPhoneRegisterFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneRegisterFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneRegisterFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox femaleCheckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox maleCheckbox;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton registerBtn1;
    private javax.swing.JTextField txtEmailRegisterForm;
    private javax.swing.JPasswordField txtPasswordRegisterForm;
    private javax.swing.JTextField txtPhoneRegisterForm;
    private javax.swing.JPasswordField txtRePasswordRegisterForm;
    private javax.swing.JTextField txtUsernameRegiserForm;
    // End of variables declaration//GEN-END:variables
}
